name: OpenHarmony gitee repos mirror periodic job

on:
  pull_request:
    paths:
    - '.github/workflows/repo-mirror.yml'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Remove unnecessary files
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Mirror the Gitee organization repos to Github.
      uses: Yikun/hub-mirror-action@v1.2
      with:
        src: gitee/openharmony
        dst: github/laiyoufafa
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.HUB_TOKEN }}
        src_account_type: org
        dst_account_type: user
        clone_style: ssh
        force_update: true
        debug: true
